project:
  type: book
  output-dir: _site

book:
  title: "Fluorescence Microscopy"
  subtitle: "M2 Microscopies — Sorbonne Université / ENS"
  author: "Jacques Fattaccioli"
  date: "2025"
  repo-url: https://github.com/fattaccioli/course-microscopy
  repo-actions: [issue]
  chapters:
    - index.qmd
    - part: "Lectures"
      chapters:
        - lectures/01-introduction.qmd
        - lectures/02-fluorescence-principles.qmd
        - lectures/03-fluorophores.qmd
        - lectures/04-microscope-in-practice.qmd
        - lectures/05-digital-imaging.qmd
        - lectures/06-advanced-techniques.qmd
        - lectures/07-ricm.qmd
        - lectures/08-two-photon.qmd
    - part: "Tutorials"
      chapters:
        - tutorials/single-molecule-microscopy.qmd


format:
  html:
    theme: flatly #cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: true
    math: mathjax
    code-fold: true
    fig-align: center
    grid:
      sidebar-width: 400px
      body-width: 1600px
      margin-width: 200px
      gutter-width: 2rem


bibliography: references.bib


